version: "3.9"

services:

  db:
    image: postgis/postgis
    restart: always
    environment:
      POSTGRES_USER: pixxeldb
      POSTGRES_PASSWORD: pixxeldb
      POSTGRES_DB: spatialdata
    ports:
      - 5432:5432
        
        
  adminer:
    image: adminer
    restart: always
    environment:
      ADMINER_DESIGN: dracula
    ports:
      - 3333:8080